# Following source doesn't work in most setups
ignored:
  - SC1090
  - SC1091
  - DL3008 # Pin versions in apt get install
  - DL3013 # Pin versions in pip
  - DL3018 # Pin versions in apk add
  - DL4006 # Set the SHELL option -o pipefail
